### ISSUE TITLE
google-files-downloader

### ISSUE THREAD

**Issue by Snzzwer** [alex2844/google-files-downloader#1]
Привет, понравился твой google-files-downloader, есть такой же только для Google "Общие диски"? Что бы на прямую на общий диск загружать торрент

**Comment by alex2844** [comment]
Добрый день.
Если имеется директория googleFilesDownloader в гугл диске - то удалите её и попробуйте заново, должен появится выбор диска

https://youtu.be/8MMIgUJuxNI?t=76

**Comment by Snzzwer** [comment]
Супер! А ограничение на диске 107 гб, больше нельзя за раз использовать?

**Comment by alex2844** [comment]
А вот это не знаю. Не могу проверить - т.к. больше у меня нет "Общего диска"

**Comment by flijloku** [comment]
Хочу присоединиться к благодарности. Сколько залито/съэкономлено трафика не сосчитать. Но имеющееся ограничение действительно немного огорчает. Нельзя залить торренты более 30Гб. Могу подарить  парочку общих дисков для экспериментов и в качестве благодарности(напишите sanset28 в телеграмме).

**Comment by alex2844** [comment]
Всем спасибо :)
Ближайщие месяца я сильно нагружен работой

**Comment by flijloku** [comment]
Тогда готов предоставить диски не в качестве аванса, а просто в знак благодарности.

**Comment by Snzzwer** [comment]
Test для sanset28

**Comment by alex2844** [comment]
@flijloku спасибо, но не надо :)
